# Generated by Django 5.2.17 on 2026-10-03 08:17

import apps.cases.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('DIAGNOSING', 'Diagnosing'), ('SECOND_OPINION', 'Second Opinion'), ('DIAGNOSED', 'Diagnosed'), ('UNKNOWN', 'Unknown'), ('PRESCRIBED', 'Prescribed'), ('EXPIRED', 'Expired'), ('PURCHASED', 'Purchased'), ('VERIFIED', 'Verified'), ('FLAGGED', 'Flagged')], db_index=True, default='REPORTED', max_length=20)),
                ('channel', models.CharField(choices=[('app', 'App'), ('whatsapp', 'Whatsapp')], default='app', max_length=16)),
                ('symptom_answers', models.JSONField(blank=True, default=dict)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CasePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('leaf', 'Leaf'), ('plant', 'Plant'), ('stem_fruit', 'Stem Fruit')], max_length=16)),
                ('image', models.ImageField(upload_to=apps.cases.models.case_photo_upload_to)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cases.case')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['farmer', '-created_at'], name='cases_case_farmer__8e6e37_idx'),
        ),
    ]
