# Generated by Django 5.2.17 on 2026-10-03 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_farm_farmerprofile'),
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='county',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='case',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='accounts.farm'),
        ),
        migrations.AddField(
            model_name='case',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='ward',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='casephoto',
            name='brightness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casephoto',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casephoto',
            name='sharpness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casephoto',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REPORTED', 'Reported'), ('DIAGNOSING', 'Diagnosing'), ('SECOND_OPINION', 'Second Opinion'), ('DIAGNOSED', 'Diagnosed'), ('UNKNOWN', 'Unknown'), ('PRESCRIBED', 'Prescribed'), ('EXPIRED', 'Expired'), ('PURCHASED', 'Purchased'), ('VERIFIED', 'Verified'), ('FLAGGED', 'Flagged')], db_index=True, default='REPORTED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['ward', 'submitted_at'], name='cases_case_ward_6a3dcf_idx'),
        ),
        migrations.AddConstraint(
            model_name='casephoto',
            constraint=models.UniqueConstraint(fields=('case', 'type'), name='cases_one_photo_per_type'),
        ),
    ]
