# Generated by Django 5.2.17 on 2026-10-03 19:49

import apps.cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_detect'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to=apps.cases.models.case_voice_note_upload_to),
        ),
    ]
