# Generated by Django 5.2.17 on 2026-10-03 17:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='Catalog key, e.g. "followups.advice.stopped"', max_length=128)),
                ('language', models.CharField(help_text='Language code, e.g. "ki"', max_length=8)),
                ('text', models.TextField()),
                ('source_text', models.TextField(help_text='The English this was translated from')),
                ('source_checksum', models.CharField(editable=False, max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=16)),
                ('translated_by', models.CharField(blank=True, max_length=128)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('language', 'key'),
                'permissions': [('approve_translation', 'Can approve translations shown to farmers')],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('key', 'language'), name='translations_one_per_key_and_language')],
            },
        ),
    ]
