# Generated by Django 5.2.17 on 2026-10-03 12:25

import apps.purchases.models
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agrovets', '0001_initial'),
        ('prescriptions', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_price_kes', models.PositiveIntegerField()),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_kes', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa (STK push)'), ('pay_at_shop', 'Reserve and pay at shop')], max_length=16)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('reserved', 'Reserved'), ('paid', 'Paid'), ('collected', 'Collected'), ('cancelled', 'Cancelled')], db_index=True, max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('agrovet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='agrovets.agrovet')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='prescriptions.prescription')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.product')),
                ('store_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='agrovets.storeitem')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_kes', models.PositiveIntegerField()),
                ('phone', models.CharField(help_text='2547XXXXXXXX', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('review', 'Review')], db_index=True, default='pending', max_length=16)),
                ('merchant_request_id', models.CharField(blank=True, max_length=64)),
                ('checkout_request_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('result_code', models.CharField(blank=True, max_length=16)),
                ('result_desc', models.CharField(blank=True, max_length=255)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('raw_callback', models.JSONField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchases.order')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=255)),
                ('failed_checks', models.PositiveIntegerField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('agrovet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flags', to='agrovets.agrovet')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('sale_match', 'Sale Match'), ('label_check', 'Label Check')], max_length=16)),
                ('result', models.CharField(choices=[('verified', 'Verified'), ('mismatch', 'Mismatch'), ('not_registered', 'Not Registered'), ('not_prescribed', 'Not Prescribed'), ('unreadable', 'Unreadable')], db_index=True, max_length=16)),
                ('detected_reg_no', models.CharField(blank=True, max_length=64)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.purchases.models.label_photo_upload_to)),
                ('ocr_text', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='purchases.order')),
                ('product', models.ForeignKey(blank=True, help_text='Product identified', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.product')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['farmer', '-created_at'], name='purchases_o_farmer__7aa15b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['agrovet', 'status'], name='purchases_o_agrovet_2ee7f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['awaiting_payment', 'reserved', 'paid'])), fields=('prescription',), name='purchases_one_active_order_per_prescription'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_kes', django.db.models.expressions.CombinedExpression(models.F('unit_price_kes'), '*', models.F('quantity')))), name='purchases_order_total_matches'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('order',), name='purchases_one_pending_payment_per_order'),
        ),
        migrations.AddConstraint(
            model_name='storeflag',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('agrovet',), name='purchases_one_open_flag_per_store'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['order', 'type', '-created_at'], name='purchases_v_order_i_e5cc75_idx'),
        ),
    ]
