# Generated by Django 5.2.17 on 2026-10-03 15:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to', models.CharField(help_text='+2547XXXXXXXX', max_length=16)),
                ('body', models.TextField()),
                ('purpose', models.CharField(choices=[('ai_result', 'Ai Result'), ('retake_photos', 'Retake Photos'), ('review_assigned', 'Review Assigned'), ('diagnosis_confirmed', 'Diagnosis Confirmed'), ('diagnosis_unknown', 'Diagnosis Unknown'), ('prescription_issued', 'Prescription Issued')], max_length=32)),
                ('source_ref', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('provider_message_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('provider_status', models.CharField(blank=True, max_length=32)),
                ('cost', models.CharField(blank=True, max_length=32)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SMS message',
                'ordering': ('-created_at',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('purpose', 'source_ref', 'to'), name='notifications_sms_once')],
            },
        ),
    ]
