# Generated by Django 5.2.17 on 2026-10-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_sms_outbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='purpose',
            field=models.CharField(choices=[('ai_result', 'Ai Result'), ('retake_photos', 'Retake Photos'), ('review_assigned', 'Review Assigned'), ('diagnosis_confirmed', 'Diagnosis Confirmed'), ('diagnosis_unknown', 'Diagnosis Unknown'), ('prescription_issued', 'Prescription Issued'), ('signup_code', 'Signup Code')], max_length=32),
        ),
    ]
