# Generated by Django 6.1.1 on 2026-10-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=15)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("in", "From user"),
                            ("out", "From AgriSense"),
                            ("stk", "M-Pesa prompt"),
                        ],
                        max_length=3,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
