# Generated by Django 5.2.17 on 2026-10-03 23:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(help_text='+2547XXXXXXXX', max_length=16, unique=True)),
                ('profile_name', models.CharField(blank=True, help_text='Name shown on the WhatsApp profile', max_length=100)),
                ('step', models.CharField(default='START', max_length=40)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wamid', models.CharField(help_text='WhatsApp message id; de-duplicates retries', max_length=200, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=16)),
                ('kind', models.CharField(max_length=16)),
                ('text', models.TextField(blank=True)),
                ('reply_id', models.CharField(blank=True, max_length=200)),
                ('media_id', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=64)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('profile_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='received', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['phone', '-created_at'], name='whatsapp_in_phone_ffa37c_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=16)),
                ('payload', models.JSONField()),
                ('source_ref', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('provider_message_id', models.CharField(blank=True, max_length=200)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_ref', ''), _negated=True), fields=('phone', 'source_ref'), name='whatsapp_notification_once')],
            },
        ),
    ]
