# Generated by Django 5.2.17 on 2026-10-03 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('verified_purchase', 'Verified Purchase'), ('case_reported', 'Case Reported'), ('referral', 'Referral'), ('redemption', 'Redemption')], max_length=32)),
                ('points', models.IntegerField()),
                ('source_ref', models.CharField(max_length=64)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reward_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'reward entries',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['farmer', '-created_at'], name='rewards_rew_farmer__e4ac87_idx')],
                'constraints': [models.UniqueConstraint(fields=('reason', 'source_ref'), name='rewards_unique_source_per_reason')],
            },
        ),
    ]
