# Generated by Django 5.2.17 on 2026-10-03 14:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('diagnosis_confirmed', 'Diagnosis Confirmed'), ('diagnosis_contradicted', 'Diagnosis Contradicted'), ('prescribing_pattern', 'Prescribing Pattern'), ('verified_purchase', 'Verified Purchase')], max_length=32)),
                ('delta', models.DecimalField(decimal_places=2, max_digits=6)),
                ('source_ref', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trust_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('user', 'reason', 'source_ref'), name='rewards_unique_trust_event')],
            },
        ),
    ]
