# Generated by Django 5.2.17 on 2026-10-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_trust_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardentry',
            name='reason',
            field=models.CharField(choices=[('verified_purchase', 'Verified Purchase'), ('case_reported', 'Case Reported'), ('follow_up', 'Follow Up'), ('referral', 'Referral'), ('redemption', 'Redemption')], max_length=32),
        ),
    ]
