# Generated by Django 6.1.1 on 2026-10-03 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcpb_reg_no', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('active_ingredients', models.JSONField(default=list)),
                ('approved_crops', models.JSONField(default=list)),
                ('label_rate_per_acre', models.DecimalField(decimal_places=2, max_digits=8)),
                ('phi_days', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_ingredient', models.CharField(max_length=120)),
                ('crop', models.CharField(default='tomato', max_length=40)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='prescribe.disease')),
            ],
        ),
    ]
