# Generated by Django 5.2.17 on 2026-10-03 15:47

import apps.followups.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_detect'),
        ('products', '0003_disease_safe_actions'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SprayRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sprayed_at', models.DateTimeField()),
                ('amount_used', models.CharField(blank=True, help_text='As the farmer says, e.g. "half the pack"', max_length=128)),
                ('baseline_share_affected', models.CharField(blank=True, choices=[('few', 'Few'), ('some', 'Some'), ('most', 'Most')], max_length=8)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Final check-in recorded', null=True)),
                ('ward', models.CharField(blank=True, max_length=64)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spray_record', to='cases.case')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.disease')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spray_records', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='purchases.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.product')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.PositiveSmallIntegerField()),
                ('new_spots', models.CharField(choices=[('spreading', 'Yes, still spreading'), ('fewer', 'A few new spots'), ('stopped', 'No new spots')], max_length=16)),
                ('share_affected', models.CharField(choices=[('few', 'Few'), ('some', 'Some'), ('most', 'Most')], max_length=8)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.followups.models.check_in_photo_upload_to)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('spray_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='followups.sprayrecord')),
            ],
            options={
                'ordering': ('day',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='sprayrecord',
            index=models.Index(fields=['disease', 'product', 'sprayed_at'], name='followups_s_disease_701aa4_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkin',
            constraint=models.UniqueConstraint(fields=('spray_record', 'day'), name='followups_one_check_in_per_day'),
        ),
    ]
