# Generated by Django 6.1.1 on 2026-10-03 19:16

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agrovet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "phone",
                    models.CharField(
                        help_text="WhatsApp number, 2547XXXXXXXX", max_length=15
                    ),
                ),
                ("county", models.CharField(max_length=50)),
                ("town", models.CharField(blank=True, max_length=80)),
                (
                    "location_hint",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Opposite Chuka market",
                        max_length=200,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Sells genuine, certified products"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="2547XXXXXXXX", max_length=15, unique=True
                    ),
                ),
                ("whatsapp_name", models.CharField(blank=True, max_length=100)),
                ("full_name", models.CharField(blank=True, max_length=100)),
                ("county", models.CharField(blank=True, max_length=50)),
                (
                    "ward",
                    models.CharField(
                        blank=True, help_text="Ward / village", max_length=80
                    ),
                ),
                ("main_crops", models.CharField(blank=True, max_length=200)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("ki", "Gĩkũyũ")],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("is_registered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop", models.CharField(max_length=50)),
                ("image", models.FileField(blank=True, upload_to="diagnoses/%Y/%m/")),
                ("wa_media_id", models.CharField(blank=True, max_length=100)),
                ("disease", models.CharField(blank=True, max_length=150)),
                ("confidence", models.FloatField(default=0)),
                ("description", models.TextField(blank=True)),
                ("treatment", models.TextField(blank=True)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("auto", "AI result sent"),
                            ("needs_review", "Waiting for agrovet"),
                            ("confirmed", "Confirmed by agrovet"),
                            ("rejected", "Corrected by agrovet"),
                        ],
                        default="auto",
                        max_length=20,
                    ),
                ),
                (
                    "agrovet_note",
                    models.TextField(
                        blank=True,
                        help_text="Sent to the farmer when you confirm/correct",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("worked", "Worked"),
                            ("partly", "Partly worked"),
                            ("no_change", "No change"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "outcome_verified",
                    models.BooleanField(
                        default=False, help_text="Agrovet checked the outcome"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.agrovet",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="core.farmer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "diagnoses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("active_ingredient", models.CharField(blank=True, max_length=120)),
                ("pack_size", models.CharField(blank=True, max_length=40)),
                ("price", models.PositiveIntegerField(help_text="KES")),
                ("farmer_discount_pct", models.PositiveSmallIntegerField(default=0)),
                (
                    "target_keywords",
                    models.CharField(
                        help_text="Comma-separated disease/pest keywords this treats, e.g. 'late blight, early blight'",
                        max_length=300,
                    ),
                ),
                (
                    "crops",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated, blank = any crop",
                        max_length=200,
                    ),
                ),
                ("usage_note", models.CharField(blank=True, max_length=300)),
                ("in_stock", models.BooleanField(default=True)),
                (
                    "agrovet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="core.agrovet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("amount", models.PositiveIntegerField(help_text="KES")),
                ("pay_phone", models.CharField(max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting payment"),
                            ("paid", "Paid"),
                            ("failed", "Payment failed"),
                            ("collected", "Collected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "checkout_request_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("mpesa_receipt", models.CharField(blank=True, max_length=30)),
                (
                    "pickup_code",
                    models.CharField(default=core.models._pickup_code, max_length=10),
                ),
                ("followup_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "diagnosis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.diagnosis",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="core.farmer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.product"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
