# Generated by Django 6.1.1 on 2026-10-03 20:45

from django.db import migrations, models


def gikuyu_to_english(apps, schema_editor):
    # Gĩkũyũ was offered but never translated; those farmers were reading English anyway.
    apps.get_model("core", "Farmer").objects.filter(language="ki").update(language="en")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Rewards for verified purchases'),
        ),
        migrations.AddField(
            model_name='order',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='label_reg_no',
            field=models.CharField(blank=True, help_text='PCPB number read from the label', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='label_result',
            field=models.CharField(blank=True, choices=[('verified', 'Verified genuine'), ('not_registered', 'Not a registered product'), ('not_prescribed', 'Registered, but not the prescribed product')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='pcpb_reg_no',
            field=models.CharField(blank=True, help_text='PCPB registration number printed on the label, e.g. "PCPB (CR) 0856"', max_length=32),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Kiswahili')], default='en', max_length=2),
        ),
        migrations.RunPython(gikuyu_to_english, migrations.RunPython.noop),
    ]
