# Generated by Django 5.2.17 on 2026-10-03 12:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agrovet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('pcpb_licence_no', models.CharField(max_length=64)),
                ('has_qualified_staff', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=16)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agrovet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_kes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('in_stock', models.BooleanField(default=True)),
                ('agrovet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='agrovets.agrovet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_items', to='products.product')),
            ],
            options={
                'ordering': ('agrovet', 'product__name'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('agrovet', 'product'), name='agrovets_one_item_per_product')],
            },
        ),
    ]
