# Generated by Django 5.2.17 on 2026-10-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_farm_farmerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='trust_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
