# Generated by Django 5.2.17 on 2026-10-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_farmer_trust_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Kiswahili'), ('ki', 'Gĩkũyũ')], default='sw', max_length=8),
        ),
    ]
