# Generated by Django 5.2.17 on 2026-10-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_kikuyu'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
