# Generated by Django 5.2.17 on 2026-10-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_kikuyu'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='sub_county',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
