# Generated by Django 5.2.17 on 2026-10-03 12:25

import apps.prescriptions.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agrovets', '0001_initial'),
        ('cases', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=apps.prescriptions.models.generate_code, editable=False, max_length=16, unique=True)),
                ('quantity', models.CharField(blank=True, help_text='Dose for the farm, e.g. "2 x 250 ml"', max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('allowed_products', models.ManyToManyField(related_name='allowed_in_prescriptions', to='products.product')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='agrovets.agrovet')),
                ('approved_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_in_prescriptions', to='products.product')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='cases.case')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
