# Generated by Django 5.2.17 on 2026-10-03 14:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_detect'),
        ('prescriptions', '0001_initial'),
        ('products', '0002_diseases_treatment_rules_dose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='products.disease'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='ranking',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='TreatmentOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('improved', models.BooleanField()),
                ('days_after_spraying', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ward', models.CharField(blank=True, max_length=64)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_outcome', to='cases.case')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.disease')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcomes', to='products.product')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['disease', 'product', '-created_at'], name='prescriptio_disease_20f10d_idx')],
            },
        ),
    ]
