# Generated by Django 5.2.17 on 2026-10-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_prescribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dose_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dose_pack_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dose_packs',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dose_unit',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
