# Generated by Django 5.2.17 on 2026-10-03 08:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDiagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('external_ref', models.CharField(blank=True, help_text='Provider identification id', max_length=64)),
                ('model_version', models.CharField(blank=True, max_length=64)),
                ('is_plant_probability', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('crop_name', models.CharField(blank=True, max_length=128)),
                ('crop_probability', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('is_plant', models.BooleanField(null=True)),
                ('is_tomato', models.BooleanField(null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_diagnoses', to='cases.case')),
            ],
            options={
                'verbose_name': 'AI diagnosis',
                'verbose_name_plural': 'AI diagnoses',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('external_id', models.CharField(help_text='Provider entity id; stable over time', max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(blank=True, max_length=255)),
                ('probability', models.DecimalField(decimal_places=4, max_digits=5)),
                ('is_healthy', models.BooleanField(default=False)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('similar_images', models.JSONField(blank=True, default=list)),
                ('ai_diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='diagnosis.aidiagnosis')),
            ],
            options={
                'ordering': ('ai_diagnosis', 'rank'),
            },
        ),
        migrations.AddIndex(
            model_name='aidiagnosis',
            index=models.Index(fields=['case', '-created_at'], name='diagnosis_a_case_id_b919d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='aidiagnosis',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'PROCESSING'])), fields=('case',), name='diagnosis_one_active_ai_run_per_case'),
        ),
        migrations.AddIndex(
            model_name='aisuggestion',
            index=models.Index(fields=['external_id'], name='diagnosis_a_externa_fece25_idx'),
        ),
        migrations.AddConstraint(
            model_name='aisuggestion',
            constraint=models.UniqueConstraint(fields=('ai_diagnosis', 'rank'), name='diagnosis_unique_suggestion_rank'),
        ),
    ]
