# Generated by Django 5.2.17 on 2026-10-03 14:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrovets', '0001_initial'),
        ('cases', '0002_detect'),
        ('diagnosis', '0001_initial'),
        ('products', '0002_diseases_treatment_rules_dose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgrovetReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.PositiveSmallIntegerField(choices=[(1, 'First'), (2, 'Second Opinion')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('decided', 'Decided'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=16)),
                ('chosen_by_farmer', models.BooleanField(default=False)),
                ('decision', models.CharField(blank=True, choices=[('disease', 'Disease'), ('unsure', 'Unsure')], max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('agrovet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='agrovets.agrovet')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agrovet_reviews', to='cases.case')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.disease')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['agrovet', 'status', '-created_at'], name='diagnosis_a_agrovet_4d9e69_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('case',), name='diagnosis_one_pending_review_per_case'), models.UniqueConstraint(fields=('case', 'agrovet'), name='diagnosis_one_review_per_agrovet')],
            },
        ),
        migrations.CreateModel(
            name='FinalDiagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=8)),
                ('ward', models.CharField(blank=True, max_length=64)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_diagnosis', to='cases.case')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_diagnoses', to='agrovets.agrovet')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_diagnoses', to='products.disease')),
            ],
            options={
                'verbose_name_plural': 'final diagnoses',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['disease', '-created_at'], name='diagnosis_f_disease_b1f989_idx'), models.Index(fields=['ward', '-created_at'], name='diagnosis_f_ward_e88734_idx')],
            },
        ),
        migrations.CreateModel(
            name='PeerComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_comments', to='cases.case')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.disease')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peer_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('case', 'farmer'), name='diagnosis_one_peer_comment_per_farmer')],
            },
        ),
    ]
