# Generated by Django 5.2.17 on 2026-10-03 19:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0003_voice_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceExchange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(max_length=8)),
                ('question', models.TextField()),
                ('answer', models.TextField(help_text='What the farmer saw')),
                ('raw_answer', models.TextField(blank=True, help_text='What the model wrote, if different')),
                ('blocked', models.BooleanField(default=False, help_text='The automatic check replaced the answer')),
                ('flags', models.JSONField(blank=True, default=dict)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('latency_s', models.FloatField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advice', to='cases.case')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['blocked', 'created_at'], name='advisory_ad_blocked_147274_idx')],
            },
        ),
    ]
