# Generated by Django 5.2.17 on 2026-10-03 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pcpb_reg_no', models.CharField(help_text='As printed, e.g. "PCPB (CR) 0856"', max_length=32)),
                ('pcpb_key', models.CharField(editable=False, help_text='Normalised lookup key', max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('active_ingredients', models.JSONField(blank=True, default=list)),
                ('approved_crops', models.JSONField(blank=True, default=list)),
                ('label_rate', models.CharField(blank=True, max_length=128)),
                ('phi_days', models.PositiveSmallIntegerField(blank=True, help_text='Pre-harvest interval', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='False if the registration is cancelled or expired')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
    ]
