# Generated by Django 5.2.17 on 2026-10-03 14:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=128)),
                ('type', models.CharField(choices=[('disease', 'Disease'), ('pest', 'Pest'), ('disorder', 'Disorder')], default='disease', max_length=16)),
                ('provider_ids', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='pack_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pack size, in rate_unit', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ppe_notes',
            field=models.TextField(blank=True, help_text='Safety notes shown on the prescription card'),
        ),
        migrations.AddField(
            model_name='product',
            name='rate_per_acre',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product per acre per spray', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rate_unit',
            field=models.CharField(blank=True, choices=[('ml', 'ml'), ('g', 'g')], max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='label_rate',
            field=models.CharField(blank=True, help_text='As printed, e.g. "50 g per 20 L"', max_length=128),
        ),
        migrations.CreateModel(
            name='TreatmentRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_ingredient', models.CharField(max_length=128)),
                ('crop', models.CharField(default='tomato', max_length=32)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_rules', to='products.disease')),
            ],
            options={
                'ordering': ('disease', 'active_ingredient'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('disease', 'active_ingredient', 'crop'), name='products_unique_treatment_rule')],
            },
        ),
    ]
