# Generated by Django 5.2.17 on 2026-10-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_diseases_treatment_rules_dose'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='local_names',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='disease',
            name='safe_actions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
