# Generated by Django 5.2.17 on 2026-10-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_disease_safe_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='explanations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
